# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_to_shoulder_joint
      - shoulder_to_arm_1_joint
      - arm_1_to_elbow_joint
      - elbow_to_arm_2_joint
      - arm_2_to_wrist_joint
      - wrist_to_end_effector_joint
    action_ns: follow_joint_trajectory
    default: true
