# This config file is used by ros2_control
# controller_manager:
#   ros__parameters:
#     update_rate: 200 # Hz

#     joint_trajectory_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

#     position_controller:
#       type: position_controllers/JointGroupPositionController

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# joint_trajectory_controller:
#   ros__parameters:
#     type: joint_trajectory_controller/JointTrajectoryController
#     allow_integration_in_goal_trajectories: false
#     allow_partial_joints_goal: false
#     cmd_timeout: 0.0
#     joints:
#       - j1
#       - j2
#       - j3
#       - j4
#       - j5
#       - j6
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#     interpolation_method: splines
#     open_loop_control: false

# position_controller:
#   ros__parameters:
#     type: position_controllers/JointGroupPositionController
#     joints:
#       - j1
#       - j2
#       - j3
#       - j4
#       - j5
#       - j6

# joint_state_broadcaster:
#   ros__parameters:
#     type: joint_state_broadcaster/JointStateBroadcaster
#     joints:
#       - j1
#       - j2
#       - j3
#       - j4
#       - j5
#       - j6
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    allow_integration_in_goal_trajectories: false
    allow_partial_joints_goal: false
    cmd_timeout: 0.0
    joints:
      - base_to_shoulder_joint
      - shoulder_to_arm_1_joint
      - arm_1_to_elbow_joint
      - elbow_to_arm_2_joint
      - arm_2_to_wrist_joint
      - wrist_to_end_effector_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    interpolation_method: splines
    open_loop_control: false

position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - base_to_shoulder_joint
      - shoulder_to_arm_1_joint
      - arm_1_to_elbow_joint
      - elbow_to_arm_2_joint
      - arm_2_to_wrist_joint
      - wrist_to_end_effector_joint

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - base_to_shoulder_joint
      - shoulder_to_arm_1_joint
      - arm_1_to_elbow_joint
      - elbow_to_arm_2_joint
      - arm_2_to_wrist_joint
      - wrist_to_end_effector_joint
